server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: oracle
    database-platform: org.hibernate.dialect.OracleDialect

logging:
  level:
    org:
      hibernate: info

app:
  cors:
    allowedOrigins: http://localhost:3000
